[package]
name = "rust5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mlua = { version = "0.6", features = ["lua53", "vendored"] }
#clap = "2.33.3"